### ISSUE TITLE
如何评价 深夜某人玩GitHub

### ISSUE THREAD

**Issue by godhelph** [AsakiRain/Weather-Card#1]
RT

**Comment by AsakiRain** [comment]
不如帮我把电脑版适配写了

**Comment by AsakiRain** [comment]
shaibi





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "AsakiRain/Weather-Card"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年4月3日(星期天) 晚上11:53
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[AsakiRain/Weather-Card] 如何评价 深夜某人玩GitHub (Issue #1)





 
RT
